function diavoloJson(){
    this.json = {
        "setting":{
            "vartion":"2013-09-26",
            "cursePrice":0,
            "plusModifierPrice":50,
            "minusModifierPrice":50,
            "capacityPrice":100,
            "entryNames":{
                "equipment":"装備ディスク",
                "memory":"記憶ディスク",
                "container":"やばいもの"
            }
        },
        "equipment":[
            {
                "name" : "スター・プラチナ",
                "part":[3,4,6],
                "remarks":"",
                "buy":17000,
                "sell":8500
            },
            {
                "name" : "シルバーチャリオッツ",
                "part":[3,5],
                "remarks":"",
                "buy":14000,
                "sell":7000
            },
            {
                "name":"キング・クリムゾン",
                "part":[5],
                "remarks":"",
                "buy":14000,
                "sell":7000
            },
            {
                "name":"エコーズACT3",
                "part":[4,5],
                "remarks":"",
                "buy":650,
                "sell":325
            },
            {
                "name":"ザ・ハンド",
                "part":[4],
                "remarks":"",
                "buy":1250,
                "sell":625
            },
            {
                "name":"チリペッパー",
                "part":[4],
                "remarks":"",
                "buy":1250,
                "sell":625
            },
            {
                "name":"クレイジー・D",
                "part":[4],
                "remarks":"",
                "buy":7000,
                "sell":3500
            },
            {
                "name":"デス・13",
                "part":[3],
                "remarks":"",
                "buy":750,
                "sell":375
            },
            {
                "name":"スティッキーフィンガーズ",
                "part":[5],
                "remarks":"",
                "buy":16000,
                "sell":8000
            },
            {
                "name":"マジシャンズレッド",
                "part":[3],
                "remarks":"",
                "buy":13200,
                "sell":6600
            },
            {
                "name":"ザ・ワールド",
                "part":[3,7],
                "remarks":"",
                "buy":15600,
                "sell":7800
            },
            {
                "name":"キラー・クィーン",
                "part":[4],
                "remarks":"",
                "buy":11700,
                "sell":5850
            },
            {
                "name":"クラッシュ",
                "part":[5],
                "remarks":"",
                "buy":3800,
                "sell":1900
            },
            {
                "name":"ホワイトスネイク",
                "part":[6],
                "remarks":"",
                "buy":9400,
                "sell":4700
            },
            {
                "name":"G・エクスペリエンス",
                "part":[5],
                "remarks":"",
                "buy":5200,
                "sell":2600
            },
            {
                "name":"ハーミットパープル",
                "part":[3,4],
                "remarks":"",
                "buy":700,
                "sell":350
            },
            {
                "name":"ダークブルームーン",
                "part":[3],
                "remarks":"",
                "buy":3800,
                "sell":1900
            },
            {
                "name":"ダイバーダウン",
                "part":[6],
                "remarks":"",
                "buy":6300,
                "sell":3150
            },
            {
                "name":"スパイスガール",
                "part":[5],
                "remarks":"",
                "buy":2850,
                "sell":1425
            },
            {
                "name":"ストーン・フリー",
                "part":[6],
                "remarks":"",
                "buy":2700,
                "sell":1350
            },
            {
                "name":"パープル・ヘイズ",
                "part":[5],
                "remarks":"",
                "buy":1000,
                "sell":500
            },
            {
                "name":"アヌビス神",
                "part":[3],
                "remarks":"確定呪いディスク",
                "buy":1000,
                "sell":500
            },
            {
                "name":"クリーム",
                "part":[3],
                "buy":11000,
                "sell":5500
            },
            {
                "name":"ムーディーブルース",
                "part":[5],
                "remarks":"",
                "buy":600,
                "sell":300
            },
            {
                "name":"リトル・フィート",
                "part":[5],
                "remarks":"",
                "buy":10500,
                "sell":5250
            },
            {
                "name":"C-MOON",
                "part":[6],
                "remarks":"",
                "buy":6000,
                "sell":3000
            },
            {
                "name":"スカイ・ハイ",
                "part":[6],
                "remarks":"",
                "buy":5800,
                "sell":2900
            },
            {
                "name":"クリーム・スターター",
                "part":[7],
                "remarks":"",
                "buy":5000,
                "sell":2500
            },
            {
                "name":"C・ザ・レインボー",
                "part":[7],
                "remarks":"",
                "buy":1800,
                "sell":900
            },
            {
                "name":"シビル・ウォー",
                "part":[7],
                "remarks":"確定呪いディスク<br />特殊呪い",
                "buy":1250,
                "sell":625
            },
                {
                "name":"イン・ア・サイレント・ウェイ",
                "part":[7],
                "remarks":"",
                "buy":3800,
                "sell":1900
            },
            {
                "name":"スケアリー・モンスターズ",
                "part":[7],
                "remarks":"",
                "buy":4800,
                "sell":2400
            },
            {
                "name":"チョコレイト・ディスコ",
                "part":[7],
                "remarks":"",
                "buy":9000,
                "sell":4500
            },
            {
                "name":"オー!ロンサム・ミー",
                "part":[7],
                "remarks":"",
                "buy":800,
                "sell":400
            },
            {
                "name":"ボールブレイカー＆スキャン",
                "part":[7],
                "remarks":"",
                "buy":10000,
                "sell":5000
            },
            {
                "name":"TATOO YOU!",
                "part":[7],
                "remarks":"",
                "buy":800,
                "sell":400
            },
            {
                "name":"GGG・オブ・ホーム",
                "part":[6],
                "remarks":"",
                "buy":1000,
                "sell":500
            },
            {
                "name":"スーパーフライ",
                "part":[4],
                "remarks":"確定呪いディスク",
                "buy":1800,
                "sell":900
            },
            {
                "name":"イエローテンパランス",
                "part":[3],
                "remarks":"",
                "buy":1500,
                "sell":750
            },
            {
                "name":"ホワイトアルバム",
                "part":[5],
                "remarks":"",
                "buy":6100,
                "sell":3050
            },
            {
                "name":"ザ・フール",
                "part":[3],
                "remarks":"",
                "buy":4400,
                "sell":2200
            },
            {
                "name":"シアーハートアタック",
                "part":[4],
                "remarks":"",
                "buy":5300,
                "sell":2650
            },
            {
                "name":"クラフトワーク",
                "part":[5],
                "remarks":"",
                "buy":3500,
                "sell":1750
            },
            {
                "name":"オアシス",
                "part":[5],
                "remarks":"",
                "buy":4200,
                "sell":2100
            },
            {
                "name":"グレイトフル・デッド",
                "part":[5],
                "remarks":"",
                "buy":2500,
                "sell":1250
            },
            {
                "name":"20th Century Boy",
                "part":[7],
                "remarks":"",
                "buy":20000,
                "sell":10000
            },
            {
                "name":"パール・ジャム",
                "part":[3],
                "remarks":"",
                "buy":2000,
                "sell":1000
            },
            {
                "name":"ハーヴェスト",
                "part":[4],
                "remarks":"",
                "buy":8800,
                "sell":4400
            },
            {
                "name":"ハイウェイ・トゥ・ヘル",
                "part":[6],
                "remarks":"確定呪いディスク",
                "buy":1500,
                "sell":750
            },
            {
                "name":"ドラゴンズドリーム",
                "part":[6],
                "remarks":"",
                "buy":7400,
                "sell":3700
            },
            {
                "name":"ウェザーリポート",
                "part":[6],
                "remarks":"",
                "buy":3900,
                "sell":1950
            },
            {
                "name":"シンデレラ",
                "part":[4],
                "remarks":"",
                "buy":7900,
                "sell":3950
            },
            {
                "name":"マンハッタントランスファー",
                "part":[6],
                "remarks":"",
                "buy":2500,
                "sell":1250
            },
            {
                "name":"エボニー・デビル",
                "part":[3],
                "remarks":"",
                "buy":2200,
                "sell":1100
            },
            {
                "name":"ソフト・マシーン",
                "part":[5],
                "remarks":"",
                "buy":4000,
                "sell":2000
            },
            {
                "name":"エンプレス",
                "part":[3],
                "remarks":"確定呪いディスク",
                "buy":700,
                "sell":350
            },
            {
                "name":"チープ・トリック",
                "part":[4],
                "remarks":"確定呪いディスク",
                "buy":1000,
                "sell":500
            },
            {
                "name":"エアロスミス",
                "part":[5],
                "remarks":"",
                "buy":8200,
                "sell":4100
            },
            {
                "name":"ハイウェイ・スター",
                "part":[4],
                "remarks":"",
                "buy":5200,
                "sell":2600
            },
            {
                "name":"ストレイ・キャット",
                "part":[4],
                "remarks":"",
                "buy":1900,
                "sell":950
            },
            {
                "name":"エピタフ",
                "part":[5],
                "remarks":"",
                "buy":3500,
                "sell":1750
            },
            {
                "name":"サバイバー",
                "part":[6],
                "remarks":"",
                "buy":1000,
                "sell":500
            },
            {
                "name":"キッス",
                "part":[6],
                "remarks":"",
                "buy":2300,
                "sell":1150
            },
            {
                "name":"ジャンピンJフラッシュ",
                "part":[6],
                "remarks":"",
                "buy":1800,
                "sell":900
            },
            {
                "name":"ボーイ2マン",
                "part":[4],
                "remarks":"",
                "buy":3400,
                "sell":1700
            },
            {
                "name":"メタリカ",
                "part":[5],
                "remarks":"",
                "buy":4200,
                "sell":2100
            },
            {
                "name":"B・D・ザ・ハウス",
                "part":[6],
                "remarks":"",
                "buy":8200,
                "sell":4100
            },
            {
                "name":"ボヘミアンラプソディ",
                "part":[6],
                "remarks":"",
                "buy":4700,
                "sell":2350
            },
            {
                "name":"キラータイガークイーン",
                "part":[4],
                "remarks":"",
                "buy":1000,
                "sell":500
            },
            {
                "name":"バイツァ・ダスト",
                "part":[4],
                "remarks":"",
                "buy":4700,
                "sell":2350
            },
            {
                "name":"メイド・イン・ヘブン",
                "part":[6],
                "remarks":"",
                "buy":10000,
                "sell":5000
            },
            {
                "name":"ヘビー・ウェザー",
                "part":[6],
                "remarks":"",
                "buy":10000,
                "sell":5000
            },
            {
                "name":"スタプラザワールド",
                "part":[3,4,6],
                "remarks":"",
                "buy":20000,
                "sell":10000
            },
            {
                "name":"G・E・レクイエム",
                "part":[5],
                "remarks":"",
                "buy":1000,
                "sell":500
            }
        ],
        "memory":[
            {
                "name":"仗助",
                "remarks":"",
                "buy":400,
                "sell":200
            },
            {
                "name":"康一",
                "remarks":"",
                "buy":1500,
                "sell":750
            },
            {
                "name":"ンドゥール",
                "remarks":"",
                "buy":400,
                "sell":200
            },
            {
                "name":"噴上裕也",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"プッチ神父",
                "remarks":"",
                "buy":400,
                "sell":200
            },
            {
                "name":"ケンゾー",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"アヴドゥル",
                "remarks":"",
                "buy":400,
                "sell":200
            },
            {
                "name":"ジョンガリ・A",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"ポルナレフ",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"ジョナサン",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"ボインゴ",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"承太郎",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"重ちー",
                "remarks":"",
                "buy":400,
                "sell":200
            },
            {
                "name":"エンポリオ",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"マニッシュボーイ",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"破裂する",
                "remarks":"",
                "buy":400,
                "sell":200
            },
            {
                "name":"ミキタカ",
                "remarks":"",
                "buy":900,
                "sell":450
            },
            {
                "name":"サンドマン",
                "remarks":"",
                "buy":1500,
                "sell":750
            },
            {
                "name":"ペットショップ",
                "remarks":"",
                "buy":1500,
                "sell":750
            },
            {
                "name":"ドッピオ",
                "remarks":"",
                "buy":1500,
                "sell":750
            },
            {
                "name":"水が熱湯になる",
                "remarks":"",
                "buy":300,
                "sell":150
            },
            {
                "name":"ディアボロ",
                "remarks":"",
                "buy":900,
                "sell":450
            },
            {
                "name":"ヌケサク",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"億泰",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"ペッシ",
                "remarks":"",
                "buy":900,
                "sell":450
            },
            {
                "name":"吉良吉影",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"J・ガイル",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"プロシュート兄貴",
                "remarks":"",
                "buy":500,
                "sell":250
            },
            {
                "name":"ギアッチョ",
                "remarks":"",
                "buy":400,
                "sell":200
            },
            {
                "name":"ポコロコ",
                "remarks":"",
                "buy":5000,
                "sell":2500
            },
            {
                "name":"ジョニィ",
                "remarks":"",
                "buy":3000,
                "sell":1500
            },
            {
                "name":"リンゴォ",
                "remarks":"",
                "buy":4200,
                "sell":2100
            },
            {
                "name":"ツェペリ",
                "remarks":"",
                "buy":900,
                "sell":450
            }
        ],
        "container":[
            {
                "name":"エニグマの紙",
                "fixation":true,
                "remarks":"2400G固定",
                "part":[4],
                "buy":2400,
                "sell":1200
            },
            {
                "name":"形兆のDISCケース",
                "fixation":false,
                "remarks":"",
                "part":[4],
                "buy":400,
                "sell":200
            },
            {
                "name":"トラクターのタイヤ",
                "fixation":false,
                "remarks":"",
                "part":[6],
                "buy":400,
                "sell":200
            },
            {
                "name":"サンジェルマンの紙袋",
                "fixation":false,
                "remarks":"",
                "part":[4],
                "buy":400,
                "sell":200
            },
            {
                "name":"露伴のカバン",
                "fixation":false,
                "remarks":"",
                "part":[4],
                "buy":400,
                "sell":200
            },
            {
                "name":"グッチョの死体",
                "fixation":false,
                "remarks":"",
                "part":[6],
                "buy":1600,
                "sell":800
            },
            {
                "name":"カルネの死体",
                "fixation":false,
                "remarks":"",
                "part":[5],
                "buy":4600,
                "sell":2300
            },
            {
                "name":"DIOの骨",
                "fixation":false,
                "remarks":"",
                "part":[6],
                "buy":4600,
                "sell":2300
            },
            {
                "name":"聖人の眼球",
                "fixation":false,
                "remarks":"",
                "part":[7],
                "buy":2400,
                "sell":1200
            },
            {
                "name":"聖人の左腕",
                "fixation":false,
                "remarks":"",
                "part":[7],
                "buy":2400,
                "sell":1200
            },
            {
                "name":"グッチのバッグ",
                "fixation":false,
                "remarks":"",
                "part":[],
                "buy":4600,
                "sell":2300
            },
            {
                "name":"エルメェスのアレ",
                "fixation":false,
                "remarks":"",
                "part":[6],
                "buy":4600,
                "sell":2300
            },
            {
                "name":"ミキタカのカバン",
                "fixation":false,
                "remarks":"",
                "part":[4],
                "buy":2400,
                "sell":1200
            },
            {
                "name":"乳母車",
                "fixation":false,
                "remarks":"",
                "part":[4],
                "buy":4600,
                "sell":2300
            },
            {
                "name":"波紋のツボ",
                "fixation":false,
                "remarks":"",
                "part":[1],
                "buy":2700,
                "sell":1350
            },
            {
                "name":"ホルマジオのビン",
                "fixation":false,
                "remarks":"",
                "part":[5],
                "buy":2500,
                "sell":1250
            },
            {
                "name":"ランドセル",
                "fixation":false,
                "remarks":"",
                "part":[4],
                "buy":2600,
                "sell":1300
            },
            {
                "name":"サーフィス人形",
                "fixation":false,
                "remarks":"",
                "part":[4],
                "buy":2800,
                "sell":1400
            },
            {
                "name":"聖人の脊椎",
                "fixation":false,
                "remarks":"",
                "part":[7],
                "buy":2900,
                "sell":1350
            },
            {
                "name":"ごま蜜団子",
                "fixation":false,
                "remarks":"",
                "part":[8],
                "buy":2700,
                "sell":1350
            }        
        ]
    }
}